/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> } 
 */

exports.seed = async function(knex) {
  // Deletes ALL existing entries
  // await knex('products').del();
  const path = require('path');
  // Insert new seed data for 25 cosmetic products with prices in VND
  await knex('products').insert([
    { name: 'L’Oreal Paris Revitalift', image_path: path.join(process.cwd(), 'Images\\asset1.jpg'), price: 690000, brand: 'L’Oreal', category: 'Skincare', description: 'Anti-aging cream', created_at: new Date(), image_thumbnail_path: null, average_rating: 3.5, stock: 100, sold: 7, num_review: 2 },
    { name: 'L’Oreal Paris Revitalift Bright Reveal',image_path: path.join(process.cwd(), 'Images\\asset2.jpg'), price: 720000, brand: 'L’Oreal', category: 'Skincare', description: 'Brightening cream for glowing skin', created_at: new Date(), image_thumbnail_path: null, average_rating: 3, stock: 200, sold: 4, num_review: 2 },
    { name: 'L’Oreal Paris Lash Paradise Mascara',image_path: path.join(process.cwd(), 'Images\\asset3.jpg'), price: 380000, brand: 'L’Oreal', category: 'Makeup', description: 'Volumizing mascara for dramatic lashes', created_at: new Date(),image_thumbnail_path: null, average_rating: 3, stock: 150, sold: 3, num_review: 2 },

    { name: 'Neutrogena Hydro Boost Water Gel',image_path: path.join(process.cwd(), 'Images\\asset4.jpg'), price: 650000, brand: 'Neutrogena', category: 'Skincare', description: 'Moisturizing gel for hydration', created_at: new Date(), image_thumbnail_path: null, average_rating: 3.5, stock: 300, sold: 3, num_review: 2 },
    { name: 'Neutrogena Oil-Free Acne Wash',image_path: path.join(process.cwd(), 'Images\\asset5.jpg'), price: 330000, brand: 'Neutrogena', category: 'Skincare', description: 'Acne treatment cleanser', created_at: new Date(),image_thumbnail_path: null, average_rating: 5, stock: 250, sold: 1, num_review: 1 },
    { name: 'Neutrogena Clear Face Sunscreen SPF 55',image_path: path.join(process.cwd(), 'Images\\asset6.jpg'), price: 270000, brand: 'Neutrogena', category: 'Skincare', description: 'Non-comedogenic sunscreen', created_at: new Date(),image_thumbnail_path: null, average_rating: 0, stock: 200, sold: 0, num_review: 0 },

    { name: 'Maybelline New York Fit Me Foundation',image_path: path.join(process.cwd(), 'Images\\asset7.jpg'), price: 320000, brand: 'Maybelline', category: 'Makeup', description: 'Matte foundation for smooth skin', created_at: new Date(), image_thumbnail_path: null, average_rating: 0, stock: 200, sold: 0, num_review: 0 },
    { name: 'Maybelline New York Lash Sensational Mascara',image_path: path.join(process.cwd(), 'Images\\asset8.jpg'), price: 250000, brand: 'Maybelline', category: 'Makeup', description: 'Lash enhancing mascara', created_at: new Date(),  image_thumbnail_path: null, average_rating: 0, stock: 150, sold: 0, num_review: 0 },
    { name: 'Maybelline New York Instant Age Rewind Concealer',image_path: path.join(process.cwd(), 'Images\\asset9.jpg'), price: 290000, brand: 'Maybelline', category: 'Makeup', description: 'Dark circle concealer', created_at: new Date(), image_thumbnail_path: null, average_rating: 0, stock: 100, sold: 0, num_review: 0 },

    { name: 'The Ordinary Niacinamide 10% + Zinc 1%',image_path: path.join(process.cwd(), 'Images\\asset10.jpg'), price: 420000, brand: 'The Ordinary', category: 'Skincare', description: 'Serum for blemish control', created_at: new Date(), image_thumbnail_path: null, average_rating: 0, stock: 200, sold: 0, num_review: 0 },
    { name: 'The Ordinary Hyaluronic Acid 2% + B5',image_path: path.join(process.cwd(), 'Images\\asset11.jpg'), price: 390000, brand: 'The Ordinary', category: 'Skincare', description: 'Hydrating serum for plump skin', created_at: new Date(),  image_thumbnail_path: null, average_rating: 0, stock: 250, sold: 0, num_review: 0 },
    { name: 'The Ordinary AHA 30% + BHA 2% Peeling Solution',image_path: path.join(process.cwd(), 'Images\\asset12.jpg'), price: 580000, brand: 'The Ordinary', category: 'Skincare', description: 'Exfoliating mask for smooth skin', created_at: new Date(),  image_thumbnail_path: null, average_rating: 0, stock: 150, sold: 0, num_review: 0 },

    { name: 'Clinique Dramatically Different Moisturizing Lotion',image_path: path.join(process.cwd(), 'Images\\asset13.jpg'), price: 880000, brand: 'Clinique', category: 'Skincare', description: 'Hydrating lotion for all skin types', created_at: new Date(),  image_thumbnail_path: null, average_rating: 0, stock: 120, sold: 0, num_review: 0 },
    { name: 'Clinique Take The Day Off Makeup Remover',image_path: path.join(process.cwd(), 'Images\\asset14.jpg'), price: 650000, brand: 'Clinique', category: 'Skincare', description: 'Makeup remover balm', created_at: new Date(), image_thumbnail_path: null, average_rating: 0, stock: 100, sold: 0, num_review: 0 },
    { name: 'Clinique Even Better Clinical Dark Spot Corrector',image_path: path.join(process.cwd(), 'Images\\asset15.jpg'), price: 1150000, brand: 'Clinique', category: 'Skincare', description: 'Dark spot treatment serum', created_at: new Date(),  image_thumbnail_path: null, average_rating: 0, stock: 90, sold: 0, num_review: 0 },

    { name: 'L’Oreal Paris Hair Spa Deep Nourishing Creambath',image_path: path.join(process.cwd(), 'Images\\asset16.jpg'), price: 450000, brand: 'L’Oreal', category: 'Haircare', description: 'Nourishing cream for healthy hair', created_at: new Date(),  image_thumbnail_path: null, average_rating: 0, stock: 200, sold: 0, num_review: 0 },
{ name: 'L’Oreal Paris Color Riche Lipstick',image_path: path.join(process.cwd(), 'Images\\asset17.jpg'), price: 320000, brand: 'L’Oreal', category: 'Makeup', description: 'Richly pigmented lipstick', created_at: new Date(),  image_thumbnail_path: null, average_rating: 0, stock: 150, sold: 0, num_review: 0 },
{ name: 'Neutrogena Ultra Sheer Dry-Touch Sunscreen SPF 100+',image_path: path.join(process.cwd(), 'Images\\asset18.jpg'), price: 370000, brand: 'Neutrogena', category: 'Skincare', description: 'High SPF sunscreen for outdoor protection', created_at: new Date(),  image_thumbnail_path: null, average_rating: 0, stock: 180, sold: 0, num_review: 0 },
{ name: 'Neutrogena Body Oil Light Sesame Formula',image_path: path.join(process.cwd(), 'Images\\asset19.jpg'), price: 580000, brand: 'Neutrogena', category: 'Bodycare', description: 'Lightweight body oil for soft skin', created_at: new Date(),   image_thumbnail_path: null, average_rating: 0, stock: 100, sold: 0, num_review: 0 },
{ name: 'Maybelline New York Colossal Kajal',image_path: path.join(process.cwd(), 'Images\\asset20.jpg'), price: 180000, brand: 'Maybelline', category: 'Makeup', description: 'Smudge-proof kajal for bold eyes', created_at: new Date(),  image_thumbnail_path: null, average_rating: 0, stock: 220, sold: 0, num_review: 0 },
{ name: 'Maybelline New York Hypercurl Mascara',image_path: path.join(process.cwd(), 'Images\\asset21.jpg'), price: 250000, brand: 'Maybelline', category: 'Makeup', description: 'Curling mascara for enhanced lashes', created_at: new Date(), image_thumbnail_path: null, average_rating: 0, stock: 180, sold: 0, num_review: 0 },
{ name: 'The Ordinary Glycolic Acid 7% Toning Solution',image_path: path.join(process.cwd(), 'Images\\asset22.jpg'), price: 490000, brand: 'The Ordinary', category: 'Skincare', description: 'Exfoliating toner for smoother skin', created_at: new Date(), image_thumbnail_path: null, average_rating: 0, stock: 150, sold: 0, num_review: 0 },
{ name: 'The Ordinary Retinol 0.5% in Squalane',image_path: path.join(process.cwd(), 'Images\\asset23.jpg'), price: 450000, brand: 'The Ordinary', category: 'Skincare', description: 'Anti-aging serum with retinol', created_at: new Date(),   image_thumbnail_path: null, average_rating: 0, stock: 120, sold: 0, num_review: 0 },
{ name: 'Clinique Moisture Surge 72-Hour Auto-Replenishing Hydrator',image_path: path.join(process.cwd(), 'Images\\asset24.jpg'), price: 1150000, brand: 'Clinique', category: 'Skincare', description: 'Long-lasting hydration gel-cream', created_at: new Date(),   image_thumbnail_path: null, average_rating: 0, stock: 100, sold: 0, num_review: 0 },
{ name: 'Clinique High Impact Mascara',image_path: path.join(process.cwd(), 'Images\\asset25.jpg'), price: 690000, brand: 'Clinique', category: 'Makeup', description: 'Volume-enhancing mascara', created_at: new Date(),   image_thumbnail_path: null, average_rating: 0, stock: 150, sold: 0, num_review: 0 },
{ name: 'Nivea Whitening Smooth Skin Roll-On',image_path: path.join(process.cwd(), 'Images\\asset26.jpg'), price: 75000, brand: 'Nivea', category: 'Bodycare', description: 'Deodorant with whitening effect', created_at: new Date(),   image_thumbnail_path: null, average_rating: 0, stock: 500, sold: 0, num_review: 0 },
{ name: 'Nivea Aloe Hydration Body Lotion',image_path: path.join(process.cwd(), 'Images\\asset27.jpg'), price: 150000, brand: 'Nivea', category: 'Bodycare', description: 'Soothing body lotion with aloe vera', created_at: new Date(),   image_thumbnail_path: null, average_rating: 0, stock: 300, sold: 0, num_review: 0 },
{ name: 'Estée Lauder Perfectly Clean Multi-Action Foam Cleanser',image_path: path.join(process.cwd(), 'Images\\asset28.jpg'), price: 1300000, brand: 'Estée Lauder', category: 'Skincare', description: 'Foaming cleanser for deep cleansing', created_at: new Date(),   image_thumbnail_path: null, average_rating: 0, stock: 90, sold: 0, num_review: 0 },
{ name: 'Estée Lauder Pure Color Envy Sculpting Lipstick',image_path: path.join(process.cwd(), 'Images\\asset29.jpg'), price: 920000, brand: 'Estée Lauder', category: 'Makeup', description: 'Sculpting lipstick with intense color', created_at: new Date(),   image_thumbnail_path: null, average_rating: 0, stock: 120, sold: 0, num_review: 0 },
{ name: 'L’Oreal Paris Extraordinary Oil Hair Serum',image_path: path.join(process.cwd(), 'Images\\asset30.jpg'), price: 350000, brand: 'L’Oreal', category: 'Haircare', description: 'Hair serum for smooth and shiny hair', created_at: new Date(),   image_thumbnail_path: null, average_rating: 0, stock: 220, sold: 0, num_review: 0 },
{ name: 'L’Oreal Paris True Match Super Blendable Foundation',image_path: path.join(process.cwd(), 'Images\\asset31.jpg'), price: 450000, brand: 'L’Oreal', category: 'Makeup', description: 'Foundation for a natural finish', created_at: new Date(),   image_thumbnail_path: null, average_rating: 0, stock: 140, sold: 0, num_review: 0 },
{ name: 'Neutrogena Hydro Boost Water Gel',image_path: path.join(process.cwd(), 'Images\\asset32.jpg'), price: 500000, brand: 'Neutrogena', category: 'Skincare', description: 'Lightweight gel for instant hydration', created_at: new Date(),   image_thumbnail_path: null, average_rating: 0, stock: 190, sold: 0, num_review: 0 },
{ name: 'Neutrogena Rapid Wrinkle Repair Night Cream',image_path: path.join(process.cwd(), 'Images\\asset33.jpg'), price: 650000, brand: 'Neutrogena', category: 'Skincare', description: 'Anti-aging night cream', created_at: new Date(),   image_thumbnail_path: null, average_rating: 0, stock: 110, sold: 0, num_review: 0 },
{ name: 'Maybelline New York Fit Me Concealer',image_path: path.join(process.cwd(), 'Images\\asset34.jpg'), price: 210000, brand: 'Maybelline', category: 'Makeup', description: 'Concealer for a flawless look', created_at: new Date(),   image_thumbnail_path: null, average_rating: 0, stock: 200, sold: 0, num_review: 0 },
{ name: 'Maybelline New York Super Stay Matte Ink',image_path: path.join(process.cwd(), 'Images\\asset35.jpg'), price: 250000, brand: 'Maybelline', category: 'Makeup', description: 'Long-lasting matte lipstick', created_at: new Date(),   image_thumbnail_path: null, average_rating: 0, stock: 180, sold: 0, num_review: 0 },
{ name: 'The Ordinary Niacinamide 10% + Zinc 1%',image_path: path.join(process.cwd(), 'Images\\asset36.jpg'), price: 420000, brand: 'The Ordinary', category: 'Skincare', description: 'Serum to reduce blemishes', created_at: new Date(),   image_thumbnail_path: null, average_rating: 0, stock: 160, sold: 0, num_review: 0 },
{ name: 'The Ordinary Caffeine Solution 5% + EGCG',image_path: path.join(process.cwd(), 'Images\\asset37.jpg'), price: 350000, brand: 'The Ordinary', category: 'Skincare', description: 'Eye serum to reduce puffiness', created_at: new Date(),   image_thumbnail_path: null, average_rating: 0, stock: 150, sold: 0, num_review: 0 },
{ name: 'Clinique Dramatically Different Moisturizing Gel',image_path: path.join(process.cwd(), 'Images\\asset38.jpg'), price: 950000, brand: 'Clinique', category: 'Skincare', description: 'Oil-free moisturizer for oily skin', created_at: new Date(),   image_thumbnail_path: null, average_rating: 0, stock: 130, sold: 0, num_review: 0 },
{ name: 'Clinique Pop Lip Colour + Primer',image_path: path.join(process.cwd(), 'Images\\asset39.jpg'), price: 750000, brand: 'Clinique', category: 'Makeup', description: 'Rich lip color with a primer', created_at: new Date(),   image_thumbnail_path: null, average_rating: 0, stock: 140, sold: 0, num_review: 0},
{ name: 'Nivea Soft Refreshingly Soft Moisturizing Cream',image_path: path.join(process.cwd(), 'Images\\asset40.jpg'), price: 130000, brand: 'Nivea', category: 'Bodycare', description: 'Soft cream for face, hands, and body', created_at: new Date(),   image_thumbnail_path: null, average_rating: 0, stock: 400, sold: 0, num_review: 0 },
{ name: 'Nivea Men Dark Spot Reduction Face Wash',image_path: path.join(process.cwd(), 'Images\\asset41.jpg'), price: 180000, brand: 'Nivea', category: 'Skincare', description: 'Face wash for men to reduce dark spots', created_at: new Date(),   image_thumbnail_path: null, average_rating: 0, stock: 250, sold: 0, num_review: 0},
{ name: 'Estée Lauder Advanced Night Repair Eye Supercharged Gel-Creme',image_path: path.join(process.cwd(), 'Images\\asset42.jpg'), price: 1450000, brand: 'Estée Lauder', category: 'Skincare', description: 'Eye gel-cream for younger-looking eyes', created_at: new Date(),   image_thumbnail_path: null, average_rating: 0, stock: 80, sold: 0, num_review: 0 },
{ name: 'Estée Lauder Double Wear Stay-In-Place Makeup',image_path: path.join(process.cwd(), 'Images\\asset43.jpg'), price: 1150000, brand: 'Estée Lauder', category: 'Makeup', description: '24-hour flawless foundation', created_at: new Date(),   image_thumbnail_path: null, average_rating: 0, stock: 100, sold: 0, num_review: 0 }

  ]);
};
